---
name: jazz

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:
    inputs:
      job:
        description: 'Job'
        required: true
        default: 'all'
        type: choice
        options:
        - 'all'
        - 'docgen'
        - 'analyze-job01'
        - 'analyze-job02'
        - 'build-job01'
        - 'build-job02'
        - 'build-job03'

defaults:
  run:
    shell: bash

jobs:

  source-job01:
    runs-on: ubuntu-20.04
    container: refenv/alpine-bash

    steps:
    - name: Do something with the source
      run: echo "Hello '${{ github.job }}' '${{ github.event.inputs.job }}'"

  source-job02:
    runs-on: ubuntu-20.04
    container: refenv/alpine-bash

    steps:
    - name: Do a pre-flight check on source
      run: echo "Hello '${{ github.job }}' '${{ github.event.inputs.job }}'"

  analyze-job01:
    needs: source-job01
    runs-on: ubuntu-latest
    container: refenv/alpine-bash
    if: (github.event_name == 'workflow_dispatch') && ((github.event.inputs.job == 'all') || (github.job == github.event.inputs.job))

    steps:
    - name: Analyze something
      run: echo "Hello '${{ github.job }}' '${{ github.event.inputs.job }}'"

  analyze-job2:
    needs: source-job01
    runs-on: ubuntu-latest
    container: refenv/alpine-bash
    if: (github.event_name == 'workflow_dispatch') && ((github.event.inputs.job == 'all') || (github.job == github.event.inputs.job))

    steps:
    - name: Analyze something
      run: echo "Hello '${{ github.job }}' '${{ github.event.inputs.job }}'"

  build-job01:
    needs: [source-job01, source-job02]
    runs-on: ubuntu-latest
    container: refenv/alpine-bash
    if: (github.event_name == 'workflow_dispatch') && ((github.event.inputs.job == 'all') || (github.job == github.event.inputs.job))

    steps:
    - name: Build something
      run: echo "Hello '${{ github.job }}' '${{ github.event.inputs.job }}'"

  build-job02:
    needs: [source-job01, source-job02]
    runs-on: ubuntu-latest
    container: refenv/alpine-bash
    if: (github.event_name == 'workflow_dispatch') && ((github.event.inputs.job == 'all') || (github.job == github.event.inputs.job))

    steps:
    - name: Build something else
      run: echo "Hello '${{ github.job }}' '${{ github.event.inputs.job }}'"

  build-job03:
    needs: [source-job01, source-job02]
    runs-on: ubuntu-latest
    container: refenv/alpine-bash
    if: (github.event_name == 'workflow_dispatch') && ((github.event.inputs.job == 'all') || (github.job == github.event.inputs.job))

    steps:
    - name: Build yet another thing
      run: echo "Hello '${{ github.job }}' '${{ github.event.inputs.job }}'"
